// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	BETTER_AUTH_URL: "http://localhost:3001" | "https://api.metaideas.workers.dev";
	BETTER_AUTH_BASE_PATH: "/auth";
	NODE_ENV: "development" | "production";
	EMAIL_FROM: "test@mail.startline.dev";
}
